Don't bundle minizinc binaries
This wasn't working because not all the binaries were bundled correctly.
In addition, not bundling the binaries means that this library is now
compatible with any OS that minizinc has binaries for, not just 64-bit
linux.

diff --git a/lib/solve b/lib/solve
--- a/lib/solve
+++ b/lib/solve
@@ -1,3 +1,8 @@
 #!/bin/sh
 
-FLATZINC_CMD=./flatzinc ./minizinc "$@"
+if command -v minizinc >&2 > /dev/null
+then
+  minizinc "$@"
+else
+  >&2 echo "'minizinc' command not found. Make sure you have added your minizinc installation to your path, eg PATH=\$PATH:/path/to/MiniZincIDE-2.2.3-bundle-linux/bin"
+fi
